In [4]:
import pandas as pd #importing pandas

df = pd.read_csv(r"C:\Users\admin\Desktop\Finance Project\finance_project_dataset.csv")
df.head() #first five entries

,Transaction_ID,Date,Customer_ID,Customer_Name,Account_Type,Transaction_Type,Amount,Branch,Channel,Loan_Status,Credit_Score
0,1001,2024-01-01,2102,Customer_0,Credit,Debit,45784.87,Mumbai,ATM,Pending,461
1,1002,2024-01-02,2435,Customer_1,Current,Debit,18438.50,Chennai,Online,Approved,646
2,1003,2024-01-03,2860,Customer_2,Current,Debit,29239.12,Chennai,Bank,Rejected,660
3,1004,2024-01-04,2270,Customer_3,Credit,Debit,31797.08,Delhi,Online,Pending,883
4,1005,2024-01-05,2106,Customer_4,Current,Debit,1148.18,Delhi,Online,Rejected,386

In [5]:
#Inspect the structure of the dataset

df.shape #rows and columns in the dataset
df.columns #column names of dataframes
df.info() #summary of dataset structure
df.describe() #statistical summary for numerical columns - mean, count, avg, etc

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    500 non-null    int64
 1   Date              500 non-null    object
 2   Customer_ID       500 non-null    int64
 3   Customer_Name     500 non-null    object
 4   Account_Type      500 non-null    object
 5   Transaction_Type  500 non-null    object
 6   Amount            500 non-null    float64
 7   Branch            500 non-null    object
 8   Channel           500 non-null    object
 9   Loan_Status       500 non-null    object
 10  Credit_Score      500 non-null    int64
dtypes: float64(1), int64(3), object(7)
memory usage: 43.1+ KB

       Transaction_ID  Customer_ID        Amount  Credit_Score
count      500.000000   500.000000    500.000000    500.000000
mean      1250.500000  2497.062000  25181.375820    601.952000
std        144.481833   288.267074  14746.707842    174.073205
min       1001.000000  2001.000000    816.100000    300.000000
25%       1125.750000  2240.750000  11864.190000    446.750000
50%       1250.500000  2494.000000  25748.865000    603.500000
75%       1375.250000  2744.750000  38170.737500    749.250000
max       1500.000000  2996.000000  49897.740000    893.000000

In [8]:
df.isnull().sum() #chk for null values
df.drop_duplicates(inplace=True) #drop the duplicates from the datasets if exist

In [10]:
df['Date'] = pd.to_datetime(df['Date']) #change the type of order_date to date instead of object
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    500 non-null    int64
 1   Date              500 non-null    datetime64[ns]
 2   Customer_ID       500 non-null    int64
 3   Customer_Name     500 non-null    object
 4   Account_Type      500 non-null    object
 5   Transaction_Type  500 non-null    object
 6   Amount            500 non-null    float64
 7   Branch            500 non-null    object
 8   Channel           500 non-null    object
 9   Loan_Status       500 non-null    object
 10  Credit_Score      500 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(6)
memory usage: 43.1+ KB

In [12]:
df['Month'] = df['Date'].dt.month #create a new column Month by extracting it
df.columns #column names of dataframes

Index(['Transaction_ID', 'Date', 'Customer_ID', 'Customer_Name',
       'Account_Type', 'Transaction_Type', 'Amount', 'Branch', 'Channel',
       'Loan_Status', 'Credit_Score', 'Month'],
      dtype='object')

In [14]:
df.to_csv("cleaned_finance_data.csv", index=False) #save the cleaned file

In [24]:
#EDA Analysis
df['Amount'].sum() #total transaction value

np.float64(12590687.91)

In [25]:
df.groupby('Account_Type')['Amount'].sum() #sum of transactions by account type

Account_Type
Credit     3837678.59
Current    4065369.39
Savings    4687639.93
Name: Amount, dtype: float64

In [26]:
df.groupby('Branch')['Amount'].sum() #sum of transactions by branch

Branch
Chennai    3018338.13
Delhi      3370579.44
Kolkata    2974497.03
Mumbai     3227273.31
Name: Amount, dtype: float64

In [28]:
df.groupby('Month')['Amount'].sum() #monthly trend of transactions

Month
1     1476537.06
2     1342483.27
3     1330291.56
4     1496473.67
5     1103916.30
6      855249.94
7      818354.79
8      818356.60
9      819681.58
10     793250.11
11     876688.37
12     859404.66
Name: Amount, dtype: float64

In [30]:
df.groupby('Customer_ID')['Amount'].sum().sort_values(ascending=False).head(10) #top ten high value customers by transaction amount

Customer_ID
2957    173097.21
2098    129321.24
2565    121180.48
2871    112500.77
2337    110181.30
2815     98054.81
2510     96012.77
2763     94748.62
2036     94651.08
2472     94007.50
Name: Amount, dtype: float64

In [31]:
df['Loan_Status'].value_counts(normalize=True) * 100 #loan approval rate

Loan_Status
Pending     33.6
Rejected    33.4
Approved    33.0
Name: proportion, dtype: float64

In [32]:
df['Channel'].value_counts() #channel usage

Channel
Online    178
ATM       173
Bank      149
Name: count, dtype: int64